// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_BSSyXAPQZCSyw8SjpK80E2Jd0Su5-8',
    appId: '1:302728306006:web:9d52600e7f67c4c3c94af7',
    messagingSenderId: '302728306006',
    projectId: 'note-app-c788b',
    authDomain: 'note-app-c788b.firebaseapp.com',
    storageBucket: 'note-app-c788b.firebasestorage.app',
    measurementId: 'G-GY767S5C7S',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhT1-jaAJ2J2JIfym2-AX4KSYMCNDkLHI',
    appId: '1:302728306006:ios:f0026afd0382df2bc94af7',
    messagingSenderId: '302728306006',
    projectId: 'note-app-c788b',
    storageBucket: 'note-app-c788b.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhT1-jaAJ2J2JIfym2-AX4KSYMCNDkLHI',
    appId: '1:302728306006:ios:f0026afd0382df2bc94af7',
    messagingSenderId: '302728306006',
    projectId: 'note-app-c788b',
    storageBucket: 'note-app-c788b.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbbZeqmr1C_se7IFD8S-IAiBMj1EN6-M',
    appId: '1:302728306006:android:dd5602c69c6aa5cfc94af7',
    messagingSenderId: '302728306006',
    projectId: 'note-app-c788b',
    storageBucket: 'note-app-c788b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk_BSSyXAPQZCSyw8SjpK80E2Jd0Su5-8',
    appId: '1:302728306006:web:29ee5986896bb28bc94af7',
    messagingSenderId: '302728306006',
    projectId: 'note-app-c788b',
    authDomain: 'note-app-c788b.firebaseapp.com',
    storageBucket: 'note-app-c788b.firebasestorage.app',
    measurementId: 'G-EFWZQ5MFFZ',
  );

}